apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: psp-access
rules:
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: psp-access
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: psp-access
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
