apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: podaccess
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: podaccess
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- kind: ServiceAccount
  name: podaccess
  namespace: default
