apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: impod
  name: impod
spec:
  containers:
  - image: nginx
    name: impod
    resources: {}
    startupProbe:
      exec:
        command:
        - rm
        - /bin/bash
      initialDelaySeconds: 5
      periodSeconds: 5
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
